Data:
  data_root:  data/VOC2012
  train_list: lists/pascal/voc_sbd_merge_noduplicate.txt
  val_list:  lists/pascal/val.txt
  classes: 16

Train:
  # Aug
  description: ""
  train_h: 473
  train_w: 473
  val_size: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  ignore_label: 255
  padding_label: 255
  # Dataset & Mode
  data_set: 'pascal'
  use_split_coco: False # True means FWB setting
  # Optimizer
  batch_size: 64 # batch size for training (bs12 for 1GPU)
  base_lr: 2.5e-4
  epochs: 200
  classification_rate: 0.5   # 0.25 means last 25% epochs for last classification training
  start_epoch: 0
  stop_interval: 200 # stop when the best result is not updated for "stop_interval" epochs
  index_split: 0 # index for determining the params group with 10x learning rate
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  warmup: 0.1
  # Viz & Save & Resume
  print_freq: 10
  save_freq: 10
  resume: # path to latest checkpoint (default: none, such as epoch_10.pth)  
  # Validate
  evaluate: True
  fix_random_seed_val: True
  batch_size_val: 64
  # Else
  workers: 64
  manual_seed: 321
  seed_deterministic: False

Method:
  layers: 50